-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 20:36:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Automerges
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `fabricante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fabricante` ;

CREATE TABLE IF NOT EXISTS `fabricante` (
  `idfabricante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`idfabricante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pieza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pieza` ;

CREATE TABLE IF NOT EXISTS `Pieza` (
  `Numero_de_pieza` INT NOT NULL AUTO_INCREMENT,
  `nombre_Pieza` VARCHAR(60) NULL,
  `Pieza_precio` FLOAT(20,2) NULL,
  `Importada` BIT NOT NULL DEFAULT 0,
  `fabricante_idfabricante` INT NOT NULL DEFAULT 0,
  `Estado_proceso` VARCHAR(50) NULL,
  PRIMARY KEY (`Numero_de_pieza`))
ENGINE = InnoDB;

CREATE INDEX `fk_Pieza_fabricante_idx` ON `Pieza` (`fabricante_idfabricante` ASC);


-- -----------------------------------------------------
-- Table `Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Persona` ;

CREATE TABLE IF NOT EXISTS `Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `dni` FLOAT(10,0) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `altura` INT NULL DEFAULT 0,
  `telefono` FLOAT(20,0) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empleado_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleado_tipo` ;

CREATE TABLE IF NOT EXISTS `empleado_tipo` (
  `idempleado_tipo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idempleado_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleado` ;

CREATE TABLE IF NOT EXISTS `empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `empleado_tipo_idempleado_tipo` INT NOT NULL,
  `sector` VARCHAR(30) NULL,
  `horario_entrada` TIME NULL,
  `horario_salida` TIME NULL,
  `is_despedido` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;

CREATE INDEX `fk_empleado_Persona1_idx` ON `empleado` (`Persona_idPersona` ASC);

CREATE INDEX `fk_empleado_empleado_tipo1_idx` ON `empleado` (`empleado_tipo_idempleado_tipo` ASC);


-- -----------------------------------------------------
-- Table `Deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Deposito` ;

CREATE TABLE IF NOT EXISTS `Deposito` (
  `idDeposito` INT NOT NULL AUTO_INCREMENT,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idDeposito`))
ENGINE = InnoDB;

CREATE INDEX `fk_Deposito_empleado1_idx` ON `Deposito` (`empleado_idempleado` ASC);


-- -----------------------------------------------------
-- Table `Pieza_has_Deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pieza_has_Deposito` ;

CREATE TABLE IF NOT EXISTS `Pieza_has_Deposito` (
  `Pieza_Numero_de_pieza` INT NOT NULL,
  `Deposito_idDeposito` INT NOT NULL,
  `stock` FLOAT(6,0) NULL,
  PRIMARY KEY (`Pieza_Numero_de_pieza`, `Deposito_idDeposito`))
ENGINE = InnoDB;

CREATE INDEX `fk_Pieza_has_Deposito_Deposito1_idx` ON `Pieza_has_Deposito` (`Deposito_idDeposito` ASC);

CREATE INDEX `fk_Pieza_has_Deposito_Pieza1_idx` ON `Pieza_has_Deposito` (`Pieza_Numero_de_pieza` ASC);


-- -----------------------------------------------------
-- Table `accion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accion` ;

CREATE TABLE IF NOT EXISTS `accion` (
  `idaccion` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(15) NULL,
  PRIMARY KEY (`idaccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

CREATE TABLE IF NOT EXISTS `cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `Persona_idPersona` INT NOT NULL,
  `clave` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;

CREATE INDEX `fk_cliente_Persona1_idx` ON `cliente` (`Persona_idPersona` ASC);


-- -----------------------------------------------------
-- Table `Vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vehiculo` ;

CREATE TABLE IF NOT EXISTS `Vehiculo` (
  `Id_auto` INT NOT NULL AUTO_INCREMENT,
  `Patente` VARCHAR(7) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `año` FLOAT(4,0) NULL,
  `accion_idaccion` INT NOT NULL,
  `cliente_idcliente` INT NULL,
  `Precio` FLOAT(30,2) NULL,
  PRIMARY KEY (`Id_auto`))
ENGINE = InnoDB;

CREATE INDEX `fk_Vehiculo_accion1_idx` ON `Vehiculo` (`accion_idaccion` ASC);

CREATE INDEX `fk_Vehiculo_cliente1_idx` ON `Vehiculo` (`cliente_idcliente` ASC);


-- -----------------------------------------------------
-- Table `Deposito_has_Vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Deposito_has_Vehiculo` ;

CREATE TABLE IF NOT EXISTS `Deposito_has_Vehiculo` (
  `Deposito_idDeposito` INT NOT NULL,
  `Vehiculo_Id_auto` INT NOT NULL,
  `estacionado` BIT NULL,
  `stock` FLOAT(6,0) NULL,
  PRIMARY KEY (`Deposito_idDeposito`, `Vehiculo_Id_auto`))
ENGINE = InnoDB;

CREATE INDEX `fk_Deposito_has_Vehiculo_Vehiculo1_idx` ON `Deposito_has_Vehiculo` (`Vehiculo_Id_auto` ASC);

CREATE INDEX `fk_Deposito_has_Vehiculo_Deposito1_idx` ON `Deposito_has_Vehiculo` (`Deposito_idDeposito` ASC);


-- -----------------------------------------------------
-- Table `estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estados` ;

CREATE TABLE IF NOT EXISTS `estados` (
  `idestados` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idestados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `informe` ;

CREATE TABLE IF NOT EXISTS `informe` (
  `idinforme` INT NOT NULL AUTO_INCREMENT,
  `asunto` VARCHAR(45) NULL,
  `estados_idestados` INT NOT NULL,
  `Vehiculo_Id_auto` INT NOT NULL,
  `Hora_de_trabajo` FLOAT(4,2) NULL DEFAULT 0,
  PRIMARY KEY (`idinforme`))
ENGINE = InnoDB;

CREATE INDEX `fk_informe_estados1_idx` ON `informe` (`estados_idestados` ASC);

CREATE INDEX `fk_informe_Vehiculo1_idx` ON `informe` (`Vehiculo_Id_auto` ASC);


-- -----------------------------------------------------
-- Table `taller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller` ;

CREATE TABLE IF NOT EXISTS `taller` (
  `idtaller` INT NOT NULL AUTO_INCREMENT,
  `Deposito_idDeposito` INT NOT NULL,
  `informe_idinforme` INT NOT NULL,
  PRIMARY KEY (`idtaller`))
ENGINE = InnoDB;

CREATE INDEX `fk_taller_Deposito1_idx` ON `taller` (`Deposito_idDeposito` ASC);

CREATE INDEX `fk_taller_informe1_idx` ON `taller` (`informe_idinforme` ASC);


-- -----------------------------------------------------
-- Table `orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orden` ;

CREATE TABLE IF NOT EXISTS `orden` (
  `idorden` INT NOT NULL AUTO_INCREMENT,
  `nombrePieza` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `taller_idtaller` INT NOT NULL,
  `Importada` BIT NULL,
  PRIMARY KEY (`idorden`))
ENGINE = InnoDB;

CREATE INDEX `fk_orden_taller1_idx` ON `orden` (`taller_idtaller` ASC);


-- -----------------------------------------------------
-- Table `factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factura` ;

CREATE TABLE IF NOT EXISTS `factura` (
  `idfactura` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `Vehiculo_Id_auto` INT NULL,
  `Pieza_Numero_de_pieza` INT NULL,
  `Precio` FLOAT(30,2) NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`idfactura`))
ENGINE = InnoDB;

CREATE INDEX `fk_factura_Vehiculo1_idx` ON `factura` (`Vehiculo_Id_auto` ASC);

CREATE INDEX `fk_factura_Pieza1_idx` ON `factura` (`Pieza_Numero_de_pieza` ASC);

CREATE INDEX `fk_factura_cliente1_idx` ON `factura` (`cliente_idcliente` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `fabricante`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `fabricante` (`idfabricante`, `nombre`) VALUES (0, 'automerges');

COMMIT;


-- -----------------------------------------------------
-- Data for table `empleado_tipo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `empleado_tipo` (`idempleado_tipo`, `Nombre`) VALUES (1, 'Ventas');
INSERT INTO `empleado_tipo` (`idempleado_tipo`, `Nombre`) VALUES (2, 'Mecanico');
INSERT INTO `empleado_tipo` (`idempleado_tipo`, `Nombre`) VALUES (5, 'Administrador');
INSERT INTO `empleado_tipo` (`idempleado_tipo`, `Nombre`) VALUES (3, 'Encargado del deposito');
INSERT INTO `empleado_tipo` (`idempleado_tipo`, `Nombre`) VALUES (4, 'fabricante');
INSERT INTO `empleado_tipo` (`idempleado_tipo`, `Nombre`) VALUES (6, 'Encargado de taller');

COMMIT;


-- -----------------------------------------------------
-- Data for table `accion`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `accion` (`idaccion`, `accion`) VALUES (1, 'Reparar');
INSERT INTO `accion` (`idaccion`, `accion`) VALUES (2, 'Restaurar');
INSERT INTO `accion` (`idaccion`, `accion`) VALUES (3, 'Comprar');
INSERT INTO `accion` (`idaccion`, `accion`) VALUES (4, 'Vender');
INSERT INTO `accion` (`idaccion`, `accion`) VALUES (5, 'Vendido');

COMMIT;


-- -----------------------------------------------------
-- Data for table `estados`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `estados` (`idestados`, `estado`) VALUES (1, 'terminado');
INSERT INTO `estados` (`idestados`, `estado`) VALUES (2, 'en proceso');
INSERT INTO `estados` (`idestados`, `estado`) VALUES (3, 'suspendido');
INSERT INTO `estados` (`idestados`, `estado`) VALUES (4, 'en cola');
INSERT INTO `estados` (`idestados`, `estado`) VALUES (5, 'rechazado');

COMMIT;

